spring:
  application:
    name: api-gateway
zuul:
  routes:
    myproduct:
      path: /myproduct/**
      serviceId: product
      sensitiveHeaders:
#    product: /myproduct/**
  ignored-patterns:
    - /**/product/listForxOrder
management:
  security:
    enabled: false  
