spring:
  application:
    name: api-gateway
  rabbitmq:
      host: 172.16.0.243
      port: 5672
      username: guest
      password: guest
zuul:
  routes:
    myproduct:
      path: /myproduct/**
      serviceId: product
      sensitiveHeaders:
#    product: /myproduct/**
  ignored-patterns:
    - /myproduct/product/listForOrder
    - /product/product/listForOrder
management:
  security:
    enabled: false  
