spring:
  application:
    name: api-gateway
  rabbitmq:
      host: 172.16.0.243
      port: 5672
      username: guest
      password: guest
zuul:
  routes:
    myproduct:
      path: /myproduct/**
      serviceId: product
      sensitiveHeaders:
      
management:
  security:
    enabled: false  
